import { appCopy as baseAppCopy, landingCopy as baseLandingCopy } from "./i18n";
import type { Language } from "./i18n";

/**
 * Product-facing copy overrides live separately from the broad translation
 * catalogue so the interface can evolve without making the data model or
 * navigation depend on marketing language.
 */
export const landingCopy: Record<Language, Record<string, string>> = {
  en: {
    ...baseLandingCopy.en,
    heroTitle: "Review candidates from application to decision.",
    heroBody: "Keep applications, interviews, feedback, and hiring decisions in one workspace, with the evidence still attached to the candidate.",
    heroProof: "Applications · interviews · feedback · decisions",
    sampleWorkspace: "HireFlow · recruiting workspace",
    flowStatusBody: "The candidate record carries the work forward.",
    latestMovement: "Updated today",
    hiringTrailTitle: "The record of a hiring decision.",
    hiringTrailBody: "See when an application arrived, what was reviewed, which conversations happened, and what was decided.",
    candidateContextTitle: "Keep the evidence beside the decision.",
    candidateContextBody: "Role context, skills, notes, and follow-up questions stay together instead of being scattered across a resume, inbox, and spreadsheet.",
    reviewableInsightBody: "Match guidance points to the application. Recruiters review the evidence and make the decision.",
    workflowTitle: "A hiring workflow your team can explain.",
    workflowBody: "Move from application to review, interview, offer, and hire with the context and next action visible at each stage.",
    securityTitle: "Useful guidance. Human decisions.",
    securityBody: "HireFlow keeps the evidence visible, records the activity around a candidate, and leaves the final decision with the hiring team.",
    securityMinded: "Responsible by default",
    securityMeta: "Reviewable guidance · role-based access · activity history",
    finalTitle: "Keep the next hiring decision in view.",
    finalBody: "Open the demo workspace to follow a candidate from application through interview and decision.",
  },
  id: {
    ...baseLandingCopy.id,
    heroTitle: "Tinjau kandidat dari lamaran hingga keputusan.",
    heroBody: "Simpan lamaran, wawancara, umpan balik, dan keputusan perekrutan dalam satu ruang kerja dengan bukti tetap melekat pada kandidat.",
    heroProof: "Lamaran · wawancara · umpan balik · keputusan",
    sampleWorkspace: "HireFlow · ruang kerja rekrutmen",
    flowStatusBody: "Catatan kandidat membawa pekerjaan ke langkah berikutnya.",
    latestMovement: "Diperbarui hari ini",
    hiringTrailTitle: "Catatan lengkap di balik keputusan perekrutan.",
    hiringTrailBody: "Lihat kapan lamaran masuk, apa yang ditinjau, percakapan yang terjadi, dan keputusan yang diambil.",
    candidateContextTitle: "Simpan bukti di dekat keputusan.",
    candidateContextBody: "Konteks posisi, keahlian, catatan, dan pertanyaan lanjutan tetap bersama, bukan tersebar di resume, kotak masuk, dan spreadsheet.",
    reviewableInsightBody: "Panduan kecocokan menunjuk ke lamaran. Perekrut meninjau bukti dan mengambil keputusan.",
    workflowTitle: "Alur perekrutan yang dapat dijelaskan tim.",
    workflowBody: "Berpindah dari lamaran ke tinjauan, wawancara, penawaran, dan perekrutan dengan konteks serta langkah berikutnya terlihat di setiap tahap.",
    securityTitle: "Panduan yang berguna. Keputusan tetap manusia.",
    securityBody: "HireFlow menjaga bukti tetap terlihat, mencatat aktivitas kandidat, dan menyerahkan keputusan akhir kepada tim perekrutan.",
    securityMinded: "Bertanggung jawab sejak awal",
    securityMeta: "Panduan yang dapat ditinjau · akses berbasis peran · riwayat aktivitas",
    finalTitle: "Jaga keputusan perekrutan berikutnya tetap terlihat.",
    finalBody: "Buka ruang kerja demo untuk mengikuti kandidat dari lamaran hingga wawancara dan keputusan.",
  },
} as const;

export const appCopy: Record<Language, Record<string, string>> = {
  en: {
    ...baseAppCopy.en,
    hiringOverview: "Hiring overview",
    dashboardIntro: "Applications, interviews, and decisions in this workspace.",
    viewPipeline: "Open candidates",
    totalCandidates: "Candidates",
    activeJobs: "Open roles",
    interviewsThisWeek: "Interviews this week",
    averageMatch: "Average match",
    recruitmentPipeline: "Hiring pipeline",
    pipelineIntro: "See who is moving, who is waiting, and what needs a decision.",
    managePipeline: "Open candidates",
    recentApplications: "Recent candidates",
    recentIntro: "Applications that need a closer look.",
    upcomingInterviews: "Upcoming interviews",
    activeActivity: "Activity history",
    activityIntro: "A record of changes in this workspace.",
    topMatches: "Review queue",
    topMatchesIntro: "Candidates waiting for a recruiter action.",
    insightDisclaimer: "Match scores are guidance. Review the resume and interview evidence.",
    talentDirectory: "Candidate directory",
    candidateIntro: "Review each application with the role, evidence, and next action in view.",
    openPositions: "Open roles",
    jobsIntro: "Open roles and the candidates attached to them.",
    pipelineEyebrow: "Work by stage",
    pipelineHelp: "Move a candidate forward after reviewing the evidence.",
    interviewSchedule: "Interview schedule",
    interviewsIntro: "See upcoming conversations and feedback still waiting to be added.",
    prepareInterview: "Before the interview",
    prepareInterviewBody: "Keep the role, candidate evidence, and agreed questions together before the conversation.",
    candidateProfile: "Candidate record",
    aiInsights: "Role match",
    strongMatches: "What aligns",
    potentialGap: "What to check",
    aiDisclaimer: "AI-generated guidance. Review the original application and interview evidence before deciding.",
  },
  id: {
    ...baseAppCopy.id,
    hiringOverview: "Ringkasan perekrutan",
    dashboardIntro: "Lamaran, wawancara, dan keputusan di ruang kerja ini.",
    viewPipeline: "Buka kandidat",
    totalCandidates: "Kandidat",
    activeJobs: "Posisi terbuka",
    interviewsThisWeek: "Wawancara minggu ini",
    averageMatch: "Rata-rata kecocokan",
    recruitmentPipeline: "Pipeline perekrutan",
    pipelineIntro: "Lihat siapa yang bergerak, siapa yang menunggu, dan apa yang membutuhkan keputusan.",
    managePipeline: "Buka kandidat",
    recentApplications: "Kandidat terbaru",
    recentIntro: "Lamaran yang perlu ditinjau lebih dekat.",
    upcomingInterviews: "Wawancara mendatang",
    activeActivity: "Riwayat aktivitas",
    activityIntro: "Catatan perubahan di ruang kerja ini.",
    topMatches: "Antrean tinjauan",
    topMatchesIntro: "Kandidat yang menunggu tindakan perekrut.",
    insightDisclaimer: "Skor kecocokan adalah panduan. Tinjau resume dan bukti wawancara.",
    talentDirectory: "Direktori kandidat",
    candidateIntro: "Tinjau setiap lamaran dengan posisi, bukti, dan langkah berikutnya tetap terlihat.",
    openPositions: "Posisi terbuka",
    jobsIntro: "Posisi terbuka dan kandidat yang terhubung dengannya.",
    pipelineEyebrow: "Pekerjaan per tahap",
    pipelineHelp: "Pindahkan kandidat setelah bukti ditinjau.",
    interviewSchedule: "Jadwal wawancara",
    interviewsIntro: "Lihat percakapan mendatang dan umpan balik yang masih perlu ditambahkan.",
    prepareInterview: "Sebelum wawancara",
    prepareInterviewBody: "Satukan posisi, bukti kandidat, dan pertanyaan yang disepakati sebelum percakapan.",
    candidateProfile: "Catatan kandidat",
    aiInsights: "Kecocokan posisi",
    strongMatches: "Yang sesuai",
    potentialGap: "Yang perlu dicek",
    aiDisclaimer: "Panduan yang dibuat AI. Tinjau lamaran asli dan bukti wawancara sebelum mengambil keputusan.",
  },
} as const;

export { getGreeting, getJobStatusLabel, getStageLabel, languageStorageKey, type Language } from "./i18n";
