"use client";

import Link from "next/link";
import Image from "next/image";
import { useMemo, useState, type ReactNode } from "react";
import { ArrowRight, Check, Clock3, FileText, Menu, ShieldCheck, Sparkles, X } from "lucide-react";
import { getStageLabel, landingCopy, Language } from "@/lib/i18n";
import { LanguageSwitcher, useLanguage } from "./language-switcher";
import hireFlowLogo from "./hireflowlogo.png";

const roles = [
  ["Senior Frontend Engineer", "Engineering", "Remote · Europe"], ["Product Designer", "Product", "London · Hybrid"],
  ["Backend Engineer", "Engineering", "Remote · UK"], ["Customer Success Manager", "Customer", "New York · Hybrid"],
] as const;
type Preview = "pipeline" | "analysis" | "interview" | "application" | "decision";

export default function LandingPage() {
  const { language, changeLanguage } = useLanguage();
  const copy = landingCopy[language];
  const [jobsOpen, setJobsOpen] = useState(false);
  const workflow = [
    ["01", copy.applicationArrives, copy.applicationBody, "application" as Preview, copy.application],
    ["02", copy.reviewWithGuidance, copy.reviewBody, "analysis" as Preview, copy.review],
    ["03", copy.interviewWithContext, copy.interviewBody, "interview" as Preview, copy.interview],
    ["04", copy.documentDecision, copy.decisionBody, "decision" as Preview, copy.decision],
  ] as const;
  return <main className="min-h-screen bg-[#fbfcfe] text-ink">
    <header className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-5 sm:px-8"><Link href="/" className="flex items-center gap-2.5"><Image src={hireFlowLogo} alt="HireFlow" className="h-9 w-9 shrink-0 object-contain" sizes="36px" priority unoptimized /><span className="text-lg font-semibold tracking-tight">HireFlow</span></Link><nav className="hidden items-center gap-7 text-sm font-medium text-slate-600 md:flex"><a href="#product" className="hover:text-ink">{copy.product}</a><a href="#workflow" className="hover:text-ink">{copy.workflow}</a><a href="#security" className="hover:text-ink">{copy.security}</a><button type="button" onClick={() => setJobsOpen(true)} className="hover:text-ink">{copy.openRoles}</button></nav><div className="flex items-center gap-2 sm:gap-3"><LanguageSwitcher language={language} onChange={changeLanguage} compact /><button type="button" onClick={() => setJobsOpen(true)} className="hidden text-sm font-semibold text-slate-700 sm:block">{copy.findJob}</button><Link href="/demo" className="rounded-xl bg-ink px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-800">{copy.exploreDemo}</Link></div></header>
    <section className="mx-auto grid max-w-7xl gap-14 px-5 pb-24 pt-14 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:gap-20 lg:pt-24"><div><p className="eyebrow">{language === "en" ? "Recruiting workspace" : "Ruang kerja rekrutmen"}</p><h1 className="mt-3 max-w-2xl text-5xl font-semibold leading-[1.04] tracking-[-.045em] sm:text-6xl">{copy.heroTitle}</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-slate-600">{copy.heroBody}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/demo" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-brand px-5 text-sm font-semibold text-white hover:bg-blue-700">{copy.exploreDemo}<ArrowRight size={17} /></Link><button type="button" onClick={() => setJobsOpen(true)} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl border bg-white px-5 text-sm font-semibold hover:bg-slate-50">{copy.viewOpenRoles}</button></div></div><div className="relative lg:pl-2"><div className="absolute -inset-3 -z-10 rounded-[2rem] bg-slate-100/80" /><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_28px_70px_rgba(24,39,75,.13)]"><div className="flex h-12 items-center gap-2 border-b px-4"><span className="h-2.5 w-2.5 rounded-full bg-slate-200" /><span className="h-2.5 w-2.5 rounded-full bg-slate-200" /><span className="h-2.5 w-2.5 rounded-full bg-slate-200" /><span className="ml-3 text-xs font-semibold text-slate-400">{copy.workspace}</span></div><div className="p-5 sm:p-7"><div className="flex items-center justify-between gap-4"><div><p className="text-sm text-slate-500">{copy.hiringOverview}</p><p className="mt-1 text-2xl font-semibold tracking-tight">{copy.openRolesShared}</p></div><span className="shrink-0 rounded-lg bg-emerald-50 px-2.5 py-1.5 text-xs font-bold text-emerald-700">{copy.active}</span></div><div className="mt-6 grid grid-cols-3 gap-3"><MiniMetric value="128" label={copy.candidates} /><MiniMetric value="82%" label={copy.averageMatch} /><MiniMetric value="18" label={copy.interviews} /></div><div className="mt-5 rounded-xl border bg-slate-50 p-4"><div className="flex items-center gap-3"><Avatar initials="MC" tone="bg-violet-100 text-violet-700" /><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="text-sm font-semibold">Maya Chen</p><p className="text-sm font-bold text-emerald-600">91%</p></div><p className="mt-0.5 text-xs text-slate-500">Senior Frontend Engineer</p></div></div><div className="mt-3 flex gap-1.5"><Tag>React</Tag><Tag>TypeScript</Tag><Tag>Design systems</Tag></div></div><p className="mt-4 text-xs leading-relaxed text-slate-500">{copy.resumeMatching}</p></div></div></div></section>
    <section id="product" className="border-y bg-white"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="max-w-xl"><p className="eyebrow">{copy.oneWorkspace}</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">{copy.productTitle}</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3"><Feature language={language} preview="pipeline" title={copy.pipelineTitle} body={copy.pipelineBody} /><Feature language={language} preview="analysis" title={copy.aiTitle} body={copy.aiBody} /><Feature language={language} preview="interview" title={copy.interviewTitle} body={copy.interviewBody} /></div></div></section>
    <section id="workflow" className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">{copy.designedAround}</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">{copy.workflowTitle}</h2><p className="mt-4 leading-relaxed text-slate-600">{copy.workflowBody}</p></div><ol className="grid gap-3 sm:grid-cols-2">{workflow.map(([number, title, body, preview, label]) => <WorkflowStep key={number} number={number} title={title} body={body} preview={preview} label={label} language={language} />)}</ol></div></section>
    <section id="security" className="bg-ink text-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 px-5 py-16 sm:px-8 md:flex-row md:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.13em] text-blue-300">{copy.builtResponsibly}</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">{copy.securityTitle}</h2><p className="mt-3 max-w-2xl leading-relaxed text-slate-300">{copy.securityBody}</p></div><div className="flex shrink-0 items-center gap-3 rounded-xl border border-slate-700 bg-white/5 p-4"><ShieldCheck className="text-blue-300" size={26} /><div><p className="text-sm font-semibold">{copy.securityMinded}</p><p className="text-xs text-slate-300">{copy.securityMeta}</p></div></div></div></section>
    <footer className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-8"><p>{copy.portfolio}</p><div className="flex gap-5"><Link href="/demo" className="font-semibold text-ink">{copy.demoWorkspace}</Link><button type="button" onClick={() => setJobsOpen(true)} className="font-semibold text-ink">{copy.jobBoard}</button></div></footer>
    {jobsOpen && <JobBoard close={() => setJobsOpen(false)} language={language} />}
  </main>;
}

function MiniMetric({ value, label }: { value: string; label: string }) { return <div className="rounded-lg border p-3"><p className="text-lg font-semibold">{value}</p><p className="mt-1 text-[11px] text-slate-500">{label}</p></div>; }
function Avatar({ initials, tone = "bg-slate-100 text-slate-700" }: { initials: string; tone?: string }) { return <span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full text-[10px] font-bold ${tone}`}>{initials}</span>; }
function Tag({ children }: { children: ReactNode }) { return <span className="rounded bg-white px-2 py-1 text-[11px] font-semibold text-slate-600">{children}</span>; }
function Feature({ language, preview, title, body }: { language: Language; preview: Preview; title: string; body: string }) { return <article className="rounded-xl border p-5 sm:p-6"><ProductPreview language={language} variant={preview} compact /><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{body}</p></article>; }
function WorkflowStep({ language, number, title, body, preview, label }: { language: Language; number: string; title: string; body: string; preview: Preview; label: string }) { return <li className="rounded-xl border bg-white p-4 sm:p-5"><div className="flex items-center justify-between"><span className="text-xs font-bold text-brand">{number}</span><span className="text-[10px] font-semibold uppercase tracking-[.12em] text-slate-400">{label}</span></div><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{body}</p><div className="mt-4"><ProductPreview language={language} variant={preview} /></div></li>; }

function ProductPreview({ language, variant, compact = false }: { language: Language; variant: Preview; compact?: boolean }) {
  const copy = landingCopy[language]; const padding = compact ? "p-3" : "p-2.5";
  if (variant === "pipeline") return <div aria-label={copy.pipelineTitle} className={`rounded-lg border bg-slate-50 ${padding}`}><div className="flex items-center justify-between"><p className="text-[10px] font-semibold uppercase tracking-[.1em] text-slate-500">{copy.pipelineTitle}</p><span className="h-1.5 w-1.5 rounded-full bg-emerald-500" /></div><div className="mt-3 grid grid-cols-4 gap-1.5">{([["Applied", "24", "bg-slate-400"], ["Screening", "8", "bg-blue-500"], ["Interview", "4", "bg-violet-500"], ["Offer", "2", "bg-emerald-500"]] as const).map(([stage, count, color]) => <div key={stage} className="min-w-0 rounded-md border bg-white p-1.5"><span className={`block h-1 w-5 rounded-full ${color}`} /><p className="mt-2 text-sm font-semibold">{count}</p><p className="truncate text-[9px] font-medium text-slate-500">{getStageLabel(language, stage)}</p></div>)}</div><div className="mt-3 flex items-center gap-2 border-t pt-2"><div className="flex -space-x-1.5"><Avatar initials="MC" tone="bg-violet-100 text-violet-700" /><Avatar initials="JL" tone="bg-sky-100 text-sky-700" /><Avatar initials="AM" tone="bg-amber-100 text-amber-700" /></div><p className="text-[10px] text-slate-500">36 {copy.candidates.toLowerCase()}</p></div></div>;
  if (variant === "analysis") return <div aria-label={copy.aiTitle} className={`rounded-lg border border-blue-100 bg-blue-50/60 ${padding}`}><div className="flex items-center justify-between"><span className="inline-flex items-center gap-1 text-[10px] font-semibold text-brand"><Sparkles size={12} />{copy.aiTitle}</span><span className="rounded bg-white px-1.5 py-0.5 text-xs font-bold text-emerald-700">87%</span></div><div className="mt-3 grid grid-cols-[1fr_auto] gap-3"><div className="space-y-1.5">{["React", "TypeScript", "REST API", "Git"].map((skill) => <p className="flex items-center gap-1.5 text-[10px] font-medium text-slate-700" key={skill}><Check size={12} className="text-emerald-600" />{skill}</p>)}</div><div className="border-l border-blue-100 pl-3"><p className="text-[9px] font-semibold uppercase tracking-[.1em] text-slate-500">{language === "en" ? "Potential gap" : "Potensi kesenjangan"}</p><p className="mt-1 text-[10px] font-semibold text-slate-700">Next.js</p></div></div><p className="mt-3 border-t border-blue-100 pt-2 text-[9px] leading-relaxed text-slate-500">{language === "en" ? "A review starting point, not an automated decision." : "Titik awal tinjauan, bukan keputusan otomatis."}</p></div>;
  if (variant === "interview") return <div aria-label={copy.interviewTitle} className={`rounded-lg border bg-slate-50 ${padding}`}><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.1em] text-slate-500">{copy.technicalInterview}</p><p className="mt-1 flex items-center gap-1 text-[10px] font-medium text-slate-600"><Clock3 size={11} />{copy.tomorrow} · 10:00</p></div><span className="rounded bg-amber-50 px-1.5 py-0.5 text-[9px] font-semibold text-amber-700">{copy.feedbackPending}</span></div><div className="mt-3 grid grid-cols-2 gap-2 border-t pt-2"><div className="flex items-center gap-1.5"><Avatar initials="AM" tone="bg-slate-200 text-slate-700" /><div><p className="text-[9px] text-slate-500">{copy.interviewer}</p><p className="text-[10px] font-semibold">Alex Morgan</p></div></div><div className="flex items-center gap-1.5"><Avatar initials="MC" tone="bg-violet-100 text-violet-700" /><div><p className="text-[9px] text-slate-500">{copy.candidate}</p><p className="text-[10px] font-semibold">Maya Chen</p></div></div></div></div>;
  if (variant === "application") return <div aria-label={copy.applicationReceived} className={`rounded-lg border bg-slate-50 ${padding}`}><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-md bg-white text-brand"><FileText size={14} /></span><div><p className="text-[10px] font-semibold">{copy.applicationReceived}</p><p className="text-[9px] text-slate-500">Maya Chen · Senior Frontend Engineer</p></div><span className="ml-auto rounded bg-blue-50 px-1.5 py-0.5 text-[9px] font-semibold text-blue-700">{getStageLabel(language, "Applied")}</span></div><div className="mt-2.5 flex gap-1.5"><Tag>{copy.resume}</Tag><Tag>{copy.profile}</Tag><Tag>{copy.jobContext}</Tag></div></div>;
  return <div aria-label={copy.candidateHistory} className={`rounded-lg border bg-slate-50 ${padding}`}><div className="flex items-center justify-between"><p className="text-[10px] font-semibold uppercase tracking-[.1em] text-slate-500">{copy.candidateHistory}</p><span className="rounded bg-emerald-50 px-1.5 py-0.5 text-[9px] font-semibold text-emerald-700">Offer</span></div><div className="mt-3 space-y-2 border-l border-slate-200 pl-3"><TimelineItem title={copy.interviewFeedback} time={`${copy.today} · 11:20`} /><TimelineItem title={copy.movedToOffer} time={`${copy.yesterday} · 16:05`} /><TimelineItem title={copy.noteAdded} time="Aug 12 · 09:40" /></div></div>;
}
function TimelineItem({ title, time }: { title: string; time: string }) { return <div className="relative"><span className="absolute -left-[15px] top-1 h-1.5 w-1.5 rounded-full bg-brand" /><p className="text-[10px] font-medium text-slate-700">{title}</p><p className="mt-0.5 text-[9px] text-slate-500">{time}</p></div>; }

function JobBoard({ close, language }: { close: () => void; language: Language }) { const copy = landingCopy[language]; const [query, setQuery] = useState(""); const visibleRoles = useMemo(() => roles.filter(([title, department, location]) => `${title} ${department} ${location}`.toLowerCase().includes(query.toLowerCase())), [query]); return <div className="fixed inset-0 z-50 overflow-y-auto bg-ink/30 p-4 sm:p-8" onClick={close}><section onClick={(event) => event.stopPropagation()} className="mx-auto max-w-3xl rounded-2xl bg-white shadow-2xl"><div className="sticky top-0 flex items-center justify-between border-b bg-white px-5 py-4"><div><p className="font-semibold">{copy.rolesAt}</p><p className="mt-0.5 text-xs text-slate-500">{copy.candidateFirst}</p></div><button type="button" onClick={close} aria-label={copy.close}><X size={20} /></button></div><div className="p-5 sm:p-7"><label className="relative block"><Menu className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16} /><span className="sr-only">{copy.searchRoles}</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={copy.searchRoles} className="h-10 w-full rounded-lg border pl-9 pr-3 text-sm outline-none focus:border-brand" /></label><div className="mt-5 divide-y">{visibleRoles.map(([title, department, location]) => <article className="flex flex-col gap-3 py-5 sm:flex-row sm:items-center" key={title}><div className="min-w-0 flex-1"><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-slate-500">{department} · {location} · {copy.fullTime}</p></div><button type="button" onClick={close} className="inline-flex h-9 items-center justify-center gap-1 rounded-lg border px-3 text-sm font-semibold text-brand hover:bg-blue-50">{copy.viewRole}<ArrowRight size={15} /></button></article>)}{visibleRoles.length === 0 && <p className="py-12 text-center text-sm text-slate-500">{language === "en" ? "No roles found." : "Posisi tidak ditemukan."}</p>}</div></div></section></div>; }
